// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HeroSliderController from "./hero_slider_controller"
application.register("hero-slider", HeroSliderController)

import ReservationFormController from "./reservation_form_controller"
application.register("reservation-form", ReservationFormController)

import StatisticsController from "./statistics_controller"
application.register("statistics", StatisticsController)

import TestController from "./test_controller"
application.register("test", TestController)
